### ISSUE TITLE
Footer  does not responsive in admin dashboard

### ISSUE THREAD

**Issue by bezael** [domini-code/mysql_node_angular#2]
![image](https://user-images.githubusercontent.com/7414771/95011933-b33b3500-0634-11eb-92e4-83a12a2375ce.png)

We have to add some style for the footer.

**Comment by qwerty-rgb** [comment]
@bezael can i take it

**Comment by qwerty-rgb** [comment]
anybody can take this

**Comment by krnithishkumar** [comment]
Fixed this issue. Check PR https://github.com/domini-code/mysql_node_angular/pull/5
